 





// Generated by PIDL compiler.
// Do not modify this file, but modify the source .pidl file.

using System;
namespace SocialC25
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID RequestLogon = (Nettention.Proud.RmiID)3000+1;
			public const Nettention.Proud.RmiID RequestAddTree = (Nettention.Proud.RmiID)3000+2;
			public const Nettention.Proud.RmiID RequestRemoveTree = (Nettention.Proud.RmiID)3000+3;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			RequestLogon,
			RequestAddTree,
			RequestRemoveTree,
		};
	}
}
namespace SocailS2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ReplyLogon = (Nettention.Proud.RmiID)4000+1;
			public const Nettention.Proud.RmiID NotifyAddTree = (Nettention.Proud.RmiID)4000+2;
			public const Nettention.Proud.RmiID NotifyRemoveTree = (Nettention.Proud.RmiID)4000+3;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ReplyLogon,
			NotifyAddTree,
			NotifyRemoveTree,
		};
	}
}
namespace SocialC2C
{
	internal class Common
	{
		// Message ID that replies to each RMI method. 
			public const Nettention.Proud.RmiID ScribblePoint = (Nettention.Proud.RmiID)5000+1;
			public const Nettention.Proud.RmiID JoyStick_Horizontal_PS1 = (Nettention.Proud.RmiID)5000+2;
			public const Nettention.Proud.RmiID JoyStick_Vertical_PS1 = (Nettention.Proud.RmiID)5000+3;
			public const Nettention.Proud.RmiID JoyStick_Horizontal_PS2 = (Nettention.Proud.RmiID)5000+4;
			public const Nettention.Proud.RmiID JoyStick_Vertical_PS2 = (Nettention.Proud.RmiID)5000+5;
			public const Nettention.Proud.RmiID Player_1Point = (Nettention.Proud.RmiID)5000+6;
			public const Nettention.Proud.RmiID Player_2Point = (Nettention.Proud.RmiID)5000+7;
		// List that has RMI ID.
		public static Nettention.Proud.RmiID[] RmiIDList = new Nettention.Proud.RmiID[] {
			ScribblePoint,
			JoyStick_Horizontal_PS1,
			JoyStick_Vertical_PS1,
			JoyStick_Horizontal_PS2,
			JoyStick_Vertical_PS2,
			Player_1Point,
			Player_2Point,
		};
	}
}

				 
